### ISSUE TITLE
feat: Add resource files

### ISSUE THREAD

**Issue by jdbaldry** [grafana/killercoda#38]
So I got this situation in a tutorial: I'm giving people a really long docker-compose.yml listing, and asking them to run it.

I can tell them to copy it into a file, but that's no fun.

I can commit it as a separate file to the KC repo, but that's no fun, because if someone modifies the docs, we now have 2 sources of truth for the docker-compose file that need to stay in sync.  

What I'd really like to say is:

```
<!-- INTERACTIVE resource "docker-compose.yml" START -->
version: '3'
services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
      - 
    command: -config.file=/etc/loki/local-config.yaml
<!-- INTERACTIVE resource "docker-compose.yml" END -->
```

You can guess what that would do.

![Image](https://github.com/grafana/killercoda/assets/5471710/44c84157-a87e-4466-ae1e-75441053ceac)
